Define initial API for data convertor
Intel-bigdata/velox pull request #11
Opened 2021-12-02 01:44 UTC by yyang52

@jikunshang @Intel-bigdata/bdf-cider-engine Please help to take a review, thanks

2021-12-02 10:46 UTC, winningsix reviewed
Do we have benchmark code and unit test code?

2021-12-02 10:46 UTC, winningsix commented on velox/omniscidb/ResultConvertor.h
> +class ResultConvertor {
From the impl behavior, it's more like a holder instead of convertor. Let's use more proper naming here.

2021-12-03 01:19 UTC, jikunshang reviewed
Please add a test or example to illustrate how to use. 
and please follow Velox code style, indent 2 spaces see [google cpp code style](https://google.github.io/styleguide/cppguide.html#Spaces_vs._Tabs)

2021-12-03 01:19 UTC, jikunshang commented on velox/omniscidb/ArrowResultConvertor.cpp
> +    void exportArrowToCider(struct ArrowArray *inputArray, struct ArrowSchema *inputSchema, CiderResultSet ciderResultSet) {
`void ArrowResultConvertor::exportArrowToCider`  same for others.

2021-12-03 01:19 UTC, jikunshang commented on velox/omniscidb/ArrowResultConvertor.cpp
> +        int8_t** col_buffer = ciderResultSet->colBuffer_;
`CiderResultSet` is a struct, should use `ciderResultSet.numRows_` instead

2021-12-03 07:48 UTC, winningsix requested changes

2021-12-03 07:48 UTC, winningsix commented on velox/omniscidb/ArrowResultConvertor.cpp
> +        int8_t** col_buffer = ciderResultSet->colBuffer_;
where did we use ```col_buffer```?

2021-12-03 07:48 UTC, winningsix commented on velox/omniscidb/ArrowResultConvertor.cpp
> +        exportToArrow(typePtr, inputSchema); // ROW({"col_0", "col_1"}, {INTEGER(), DOUBLE()})
did we have all related code here? I dind't find definition for ```exportToArrow```.

2021-12-03 07:59 UTC, yyang52 commented on velox/omniscidb/ArrowResultConvertor.cpp
> +        exportToArrow(typePtr, inputSchema); // ROW({"col_0", "col_1"}, {INTEGER(), DOUBLE()})
exportToArrow is already implemented by facebook (under vector/arrow/Bridge.cpp), assume that could be used?

2021-12-03 08:00 UTC, yyang52 commented on velox/omniscidb/ArrowResultConvertor.cpp
> +        int8_t** col_buffer = ciderResultSet->colBuffer_;
col_buffer store the real data

2021-12-03 08:03 UTC, jikunshang commented on velox/omniscidb/ArrowResultConvertor.cpp
> +        int8_t** col_buffer = ciderResultSet->colBuffer_;
cider kernel will use `col_buffer`

2021-12-03 08:08 UTC, yyang52 commented on velox/omniscidb/ArrowResultConvertor.cpp
> +    void exportArrowToCider(struct ArrowArray *inputArray, struct ArrowSchema *inputSchema, CiderResultSet ciderResultSet) {
fixed in the new commit

2021-12-03 08:08 UTC, yyang52 commented on velox/omniscidb/ResultConvertor.h
> +class ResultConvertor {
fixed in the new commit

2021-12-03 08:16 UTC, yma11 commented on velox/omniscidb/ResultHolder.cpp
> +
so exportToCider = convertToCider, convertToRowVector=importFromCider, why do you implement these kind of duplicated methods?

2021-12-03 08:22 UTC, jikunshang commented on velox/omniscidb/ResultHolder.h
> +class ResultHolder {
what's  the relationship between `ResultHolder` and `ResultConvertor` ?

2021-12-03 08:31 UTC, winningsix commented on velox/omniscidb/ArrowResultConvertor.cpp
> +        int8_t** col_buffer = ciderResultSet->colBuffer_;
I mean within this method. Did we use that variable?

2021-12-05 14:33 UTC, yyang52 commented on velox/omniscidb/ResultHolder.h
> +class ResultHolder {
Actually the same, but change name as suggested by Cheng. Forgot to remove those original files at first, fixed now~

2021-12-05 14:33 UTC, yyang52 commented on velox/omniscidb/ResultHolder.cpp
> +
Those inner functions serve like a placeholder to indicate the wrapper functions may have several sub-functions. I will fix that if no need to implement that way.

2021-12-05 14:33 UTC, yyang52 commented on velox/omniscidb/ArrowResultConvertor.cpp
> +        int8_t** col_buffer = ciderResultSet->colBuffer_;
please check ArrowResultHolder, though still wip

2021-12-06 08:25 UTC, winningsix commented on velox/omnisci/ResultHolder.h
> +class ResultHolder {
Maybe ```DataHolder``` more precise?

2021-12-06 08:25 UTC, winningsix commented on velox/omnisci/ResultHolder.h
> +  static std::shared_ptr<ResultHolder> create(int flag);
Add comments for ```flag```. BTW, when we should use non-direct?

2021-12-06 08:25 UTC, winningsix commented
Empty file ```ArrowResultHolder.cpp``` and ```velox/omnisci/RawResultHolder.cpp```?

2021-12-06 08:35 UTC, yyang52 commented on velox/omnisci/ResultHolder.h
> +class ResultHolder {
change to DataConvertor as the classes do not hold state now

2021-12-06 08:35 UTC, yyang52 commented on velox/omnisci/ResultHolder.h
> +  static std::shared_ptr<ResultHolder> create(int flag);
refactored

2021-12-07 09:26 UTC, jikunshang reviewed
Please remove unused files like `resultholder`

2021-12-07 09:26 UTC, jikunshang commented on velox/omnisci/ArrowDataConvertor.cpp
> +  CiderResultSet convertToCider(RowVectorPtr input, int num_rows) override {
please add todo is you didn't impl it yet.

2021-12-07 09:26 UTC, jikunshang commented on velox/omnisci/ArrowDataConvertor.cpp
> +  CiderResultSet convertToCider(RowVectorPtr input, int num_rows) override {
`ArrowDataConvertor::convertToCider`

2021-12-10 02:15 UTC, jikunshang reviewed
please use code format tool.

2021-12-10 02:15 UTC, jikunshang commented on velox/omnisci/RawDataConvertor.cpp
> +  void convert(VectorPtr& child, int idx, int8_t** col_buffer, int num_rows) {
this is same definition to Line 34?

2021-12-10 02:15 UTC, jikunshang commented on velox/omnisci/RawDataConvertor.cpp
> +          convert<bool>(VectorPtr& child, int idx, int8_t** col_buffer)
I suggest not use template since you are not familiar with that.

2021-12-13 03:31 UTC, jikunshang commented on velox/omnisci/tests/CMakeLists.txt
> +  ${gflags_LIBRARIES}
necessary dependency?

2021-12-13 03:31 UTC, jikunshang commented on velox/omnisci/RawDataConvertor.cpp
> +          bool* column = (bool*)std::malloc(sizeof(bool) * num_rows);
when will free?

2021-12-13 03:31 UTC, jikunshang commented on velox/omnisci/RawDataConvertor.cpp
> +                rawValues[pos] = std::numeric_limits<bool>::min() + 1;
why use this? I suggest to copy omnisci defination and use that one.
And seems this part could be refactored since they have similar impl for different type?

2021-12-13 03:31 UTC, jikunshang commented on velox/omnisci/RawDataConvertor.cpp
> +  VectorPtr convertColumn(const TypePtr& vType, int8_t* data_buffer, int num_rows, memory::MemoryPool* pool) {
this is just a util function? any possibility to reuse or be a method of some class?

2021-12-13 03:35 UTC, yyang52 commented on velox/omnisci/tests/CMakeLists.txt
> +  ${gflags_LIBRARIES}
will remove the last one

2021-12-13 03:45 UTC, yyang52 commented on velox/omnisci/RawDataConvertor.cpp
> +                rawValues[pos] = std::numeric_limits<bool>::min() + 1;
I think this is just the omnisci's defination? will double check
template <class T>
constexpr inline int64_t inline_int_null_array_value() {
  return std::is_signed<T>::value ? std::numeric_limits<T>::min() + 1
                                  : std::numeric_limits<T>::max() - 1;

2021-12-13 04:40 UTC, jikunshang commented on velox/omnisci/RawDataConvertor.cpp
> +                rawValues[pos] = std::numeric_limits<bool>::min() + 1;
OK that's good, I thought omnisci will use these macros 
`#define NULL_INT INT32_MIN`

2021-12-13 05:02 UTC, jikunshang commented
I will merge this PR for now. 
Please fix known issues in further changes, thanks.

2021-12-13 05:03 UTC, merged

2021-12-13 05:11 UTC, jikunshang commented
Forget to choose `squash and merge` option, can you set this as default configuration in repo settings @winningsix , thanks!